package com.mvne.app.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.stereotype.Component;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_acct
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Component
public class CmAcct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.ACCT_ID
     *
     * @mbggenerated
     */
    private Integer acctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.CUST_ID
     *
     * @mbggenerated
     */
    private Integer custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.BILL_ID
     *
     * @mbggenerated
     */
    private String billId;

    /**
     * Database Column Remarks:
     *   1	准预付
     *               0	后付
     *               
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.ACCT_TYPE
     *
     * @mbggenerated
     */
    private String acctType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.MVNO_ID
     *
     * @mbggenerated
     */
    private String mvnoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.PROV_CODE
     *
     * @mbggenerated
     */
    private String provCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   1：正常
     *               0：失效
     *               
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.STATE_CHG_DATE
     *
     * @mbggenerated
     */
    private Date stateChgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_acct.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.ACCT_ID
     *
     * @return the value of cm_acct.ACCT_ID
     *
     * @mbggenerated
     */
    public Integer getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.ACCT_ID
     *
     * @param acctId the value for cm_acct.ACCT_ID
     *
     * @mbggenerated
     */
    public void setAcctId(Integer acctId) {
        this.acctId = acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.CUST_ID
     *
     * @return the value of cm_acct.CUST_ID
     *
     * @mbggenerated
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.CUST_ID
     *
     * @param custId the value for cm_acct.CUST_ID
     *
     * @mbggenerated
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.BILL_ID
     *
     * @return the value of cm_acct.BILL_ID
     *
     * @mbggenerated
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.BILL_ID
     *
     * @param billId the value for cm_acct.BILL_ID
     *
     * @mbggenerated
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.ACCT_TYPE
     *
     * @return the value of cm_acct.ACCT_TYPE
     *
     * @mbggenerated
     */
    public String getAcctType() {
        return acctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.ACCT_TYPE
     *
     * @param acctType the value for cm_acct.ACCT_TYPE
     *
     * @mbggenerated
     */
    public void setAcctType(String acctType) {
        this.acctType = acctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.MVNO_ID
     *
     * @return the value of cm_acct.MVNO_ID
     *
     * @mbggenerated
     */
    public String getMvnoId() {
        return mvnoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.MVNO_ID
     *
     * @param mvnoId the value for cm_acct.MVNO_ID
     *
     * @mbggenerated
     */
    public void setMvnoId(String mvnoId) {
        this.mvnoId = mvnoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.PROV_CODE
     *
     * @return the value of cm_acct.PROV_CODE
     *
     * @mbggenerated
     */
    public String getProvCode() {
        return provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.PROV_CODE
     *
     * @param provCode the value for cm_acct.PROV_CODE
     *
     * @mbggenerated
     */
    public void setProvCode(String provCode) {
        this.provCode = provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.AREA_CODE
     *
     * @return the value of cm_acct.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.AREA_CODE
     *
     * @param areaCode the value for cm_acct.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.BALANCE
     *
     * @return the value of cm_acct.BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.BALANCE
     *
     * @param balance the value for cm_acct.BALANCE
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.STATE
     *
     * @return the value of cm_acct.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.STATE
     *
     * @param state the value for cm_acct.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.STATE_CHG_DATE
     *
     * @return the value of cm_acct.STATE_CHG_DATE
     *
     * @mbggenerated
     */
    public Date getStateChgDate() {
        return stateChgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.STATE_CHG_DATE
     *
     * @param stateChgDate the value for cm_acct.STATE_CHG_DATE
     *
     * @mbggenerated
     */
    public void setStateChgDate(Date stateChgDate) {
        this.stateChgDate = stateChgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.CREATE_DATE
     *
     * @return the value of cm_acct.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.CREATE_DATE
     *
     * @param createDate the value for cm_acct.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_acct.REMARK
     *
     * @return the value of cm_acct.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_acct.REMARK
     *
     * @param remark the value for cm_acct.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}