package com.mvne.app.domain;

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subs_product_element
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Component
public class SubsProductElement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer subsElementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer subsProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.SUBS_USER_ID
     *
     * @mbggenerated
     */
    private Integer subsUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer elementId;

    /**
     * Database Column Remarks:
     *   BSS核心:不可空字段
     *               BSS整改:可空
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   AMOUNT：余额中心相关元素
     *               MU：通讯类资费相关元素
     *               MATERIAL：实物元素
     *               PROTO：协议元素（���补贴）
     *               DEPOSIT：押金
     *               
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.ELEMENT_TYPE
     *
     * @mbggenerated
     */
    private String elementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.EXPIRE_DATE
     *
     * @mbggenerated
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.PROV_CODE
     *
     * @mbggenerated
     */
    private String provCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_product_element.OPER_ID
     *
     * @mbggenerated
     */
    private Integer operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.SUBS_ELEMENT_ID
     *
     * @return the value of subs_product_element.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsElementId() {
        return subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.SUBS_ELEMENT_ID
     *
     * @param subsElementId the value for subs_product_element.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setSubsElementId(Integer subsElementId) {
        this.subsElementId = subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.SUBS_PRODUCT_ID
     *
     * @return the value of subs_product_element.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsProductId() {
        return subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.SUBS_PRODUCT_ID
     *
     * @param subsProductId the value for subs_product_element.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setSubsProductId(Integer subsProductId) {
        this.subsProductId = subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.SUBS_USER_ID
     *
     * @return the value of subs_product_element.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public Integer getSubsUserId() {
        return subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.SUBS_USER_ID
     *
     * @param subsUserId the value for subs_product_element.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public void setSubsUserId(Integer subsUserId) {
        this.subsUserId = subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.ELEMENT_ID
     *
     * @return the value of subs_product_element.ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.ELEMENT_ID
     *
     * @param elementId the value for subs_product_element.ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.PRODUCT_ID
     *
     * @return the value of subs_product_element.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.PRODUCT_ID
     *
     * @param productId the value for subs_product_element.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.ELEMENT_TYPE
     *
     * @return the value of subs_product_element.ELEMENT_TYPE
     *
     * @mbggenerated
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.ELEMENT_TYPE
     *
     * @param elementType the value for subs_product_element.ELEMENT_TYPE
     *
     * @mbggenerated
     */
    public void setElementType(String elementType) {
        this.elementType = elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.CREATE_DATE
     *
     * @return the value of subs_product_element.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.CREATE_DATE
     *
     * @param createDate the value for subs_product_element.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.EFFECTIVE_DATE
     *
     * @return the value of subs_product_element.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for subs_product_element.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.EXPIRE_DATE
     *
     * @return the value of subs_product_element.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.EXPIRE_DATE
     *
     * @param expireDate the value for subs_product_element.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.PROV_CODE
     *
     * @return the value of subs_product_element.PROV_CODE
     *
     * @mbggenerated
     */
    public String getProvCode() {
        return provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.PROV_CODE
     *
     * @param provCode the value for subs_product_element.PROV_CODE
     *
     * @mbggenerated
     */
    public void setProvCode(String provCode) {
        this.provCode = provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.AREA_CODE
     *
     * @return the value of subs_product_element.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.AREA_CODE
     *
     * @param areaCode the value for subs_product_element.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_product_element.OPER_ID
     *
     * @return the value of subs_product_element.OPER_ID
     *
     * @mbggenerated
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_product_element.OPER_ID
     *
     * @param operId the value for subs_product_element.OPER_ID
     *
     * @mbggenerated
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }
}