package com.mvne.app.domain;

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subs_comm
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Component
public class SubsComm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer subsElementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer subsProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.SUBS_USER_ID
     *
     * @mbggenerated
     */
    private Integer subsUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer elementId;

    /**
     * Database Column Remarks:
     *   1：自定义
     *               0：标准  （这个字段来标示是否需要记载subs_comm_res数据，0时不加载）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.DEFINE_FLAG
     *
     * @mbggenerated
     */
    private String defineFlag;

    /**
     * Database Column Remarks:
     *   100 ：H计划  作废，由101取代   
     *               101 ：独享
     *               102 ：共享
     *               103 ：保底消费
     *               200 ：应用类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.COMM_TYPE
     *
     * @mbggenerated
     */
    private String commType;

    /**
     * Database Column Remarks:
     *   1-标准产品模式
     *               2-资源模式
     *               3-虚拟币模式
     *               4-即买即用专用资源
     *               5-即买即用通用资源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.COMM_CATA
     *
     * @mbggenerated
     */
    private Short commCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.COMM_TOTAL_FEE
     *
     * @mbggenerated
     */
    private Long commTotalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.COMM_ADJUST_FEE
     *
     * @mbggenerated
     */
    private Long commAdjustFee;

    /**
     * Database Column Remarks:
     *   通信资源转兑周期，单位：月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.COMM_RES_RECYLE
     *
     * @mbggenerated
     */
    private Short commResRecyle;

    /**
     * Database Column Remarks:
     *   0-按月清零：RES_CLEAR_CYCLE字段填写单位为月，1代表当月新转兑资源当月月底失效清零；2代表当月新转兑资源次月月底失效清零，999代表永久不失效
     *               1-不清零
     *               2-按自然年清零：RES_CLEAR_CYCLE字段填写单位为自然年，0代表当年年底最后一天，1代表次年年底最后一天，依此类推
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.RES_CLEAR_FLAG
     *
     * @mbggenerated
     */
    private Short resClearFlag;

    /**
     * Database Column Remarks:
     *   单位：月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.RES_CLEAR_CYCLE
     *
     * @mbggenerated
     */
    private Short resClearCycle;

    /**
     * Database Column Remarks:
     *   0-非赠送
     *               1-赠送
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.RES_BONUS_FLAG
     *
     * @mbggenerated
     */
    private String resBonusFlag;

    /**
     * Database Column Remarks:
     *   1- 适应（与产品生失效时间保持一致）
     *               2-永久生效（2099-12-31）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.RES_END_TYPE
     *
     * @mbggenerated
     */
    private String resEndType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.PROV_CODE
     *
     * @mbggenerated
     */
    private String provCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.EXPIRE_DATE
     *
     * @mbggenerated
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_comm.OPER_ID
     *
     * @mbggenerated
     */
    private Integer operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.SUBS_ELEMENT_ID
     *
     * @return the value of subs_comm.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsElementId() {
        return subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.SUBS_ELEMENT_ID
     *
     * @param subsElementId the value for subs_comm.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setSubsElementId(Integer subsElementId) {
        this.subsElementId = subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.SUBS_PRODUCT_ID
     *
     * @return the value of subs_comm.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsProductId() {
        return subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.SUBS_PRODUCT_ID
     *
     * @param subsProductId the value for subs_comm.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setSubsProductId(Integer subsProductId) {
        this.subsProductId = subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.SUBS_USER_ID
     *
     * @return the value of subs_comm.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public Integer getSubsUserId() {
        return subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.SUBS_USER_ID
     *
     * @param subsUserId the value for subs_comm.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public void setSubsUserId(Integer subsUserId) {
        this.subsUserId = subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.ELEMENT_ID
     *
     * @return the value of subs_comm.ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.ELEMENT_ID
     *
     * @param elementId the value for subs_comm.ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.DEFINE_FLAG
     *
     * @return the value of subs_comm.DEFINE_FLAG
     *
     * @mbggenerated
     */
    public String getDefineFlag() {
        return defineFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.DEFINE_FLAG
     *
     * @param defineFlag the value for subs_comm.DEFINE_FLAG
     *
     * @mbggenerated
     */
    public void setDefineFlag(String defineFlag) {
        this.defineFlag = defineFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.COMM_TYPE
     *
     * @return the value of subs_comm.COMM_TYPE
     *
     * @mbggenerated
     */
    public String getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.COMM_TYPE
     *
     * @param commType the value for subs_comm.COMM_TYPE
     *
     * @mbggenerated
     */
    public void setCommType(String commType) {
        this.commType = commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.COMM_CATA
     *
     * @return the value of subs_comm.COMM_CATA
     *
     * @mbggenerated
     */
    public Short getCommCata() {
        return commCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.COMM_CATA
     *
     * @param commCata the value for subs_comm.COMM_CATA
     *
     * @mbggenerated
     */
    public void setCommCata(Short commCata) {
        this.commCata = commCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.COMM_TOTAL_FEE
     *
     * @return the value of subs_comm.COMM_TOTAL_FEE
     *
     * @mbggenerated
     */
    public Long getCommTotalFee() {
        return commTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.COMM_TOTAL_FEE
     *
     * @param commTotalFee the value for subs_comm.COMM_TOTAL_FEE
     *
     * @mbggenerated
     */
    public void setCommTotalFee(Long commTotalFee) {
        this.commTotalFee = commTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.COMM_ADJUST_FEE
     *
     * @return the value of subs_comm.COMM_ADJUST_FEE
     *
     * @mbggenerated
     */
    public Long getCommAdjustFee() {
        return commAdjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.COMM_ADJUST_FEE
     *
     * @param commAdjustFee the value for subs_comm.COMM_ADJUST_FEE
     *
     * @mbggenerated
     */
    public void setCommAdjustFee(Long commAdjustFee) {
        this.commAdjustFee = commAdjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.COMM_RES_RECYLE
     *
     * @return the value of subs_comm.COMM_RES_RECYLE
     *
     * @mbggenerated
     */
    public Short getCommResRecyle() {
        return commResRecyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.COMM_RES_RECYLE
     *
     * @param commResRecyle the value for subs_comm.COMM_RES_RECYLE
     *
     * @mbggenerated
     */
    public void setCommResRecyle(Short commResRecyle) {
        this.commResRecyle = commResRecyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.RES_CLEAR_FLAG
     *
     * @return the value of subs_comm.RES_CLEAR_FLAG
     *
     * @mbggenerated
     */
    public Short getResClearFlag() {
        return resClearFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.RES_CLEAR_FLAG
     *
     * @param resClearFlag the value for subs_comm.RES_CLEAR_FLAG
     *
     * @mbggenerated
     */
    public void setResClearFlag(Short resClearFlag) {
        this.resClearFlag = resClearFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.RES_CLEAR_CYCLE
     *
     * @return the value of subs_comm.RES_CLEAR_CYCLE
     *
     * @mbggenerated
     */
    public Short getResClearCycle() {
        return resClearCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.RES_CLEAR_CYCLE
     *
     * @param resClearCycle the value for subs_comm.RES_CLEAR_CYCLE
     *
     * @mbggenerated
     */
    public void setResClearCycle(Short resClearCycle) {
        this.resClearCycle = resClearCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.RES_BONUS_FLAG
     *
     * @return the value of subs_comm.RES_BONUS_FLAG
     *
     * @mbggenerated
     */
    public String getResBonusFlag() {
        return resBonusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.RES_BONUS_FLAG
     *
     * @param resBonusFlag the value for subs_comm.RES_BONUS_FLAG
     *
     * @mbggenerated
     */
    public void setResBonusFlag(String resBonusFlag) {
        this.resBonusFlag = resBonusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.RES_END_TYPE
     *
     * @return the value of subs_comm.RES_END_TYPE
     *
     * @mbggenerated
     */
    public String getResEndType() {
        return resEndType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.RES_END_TYPE
     *
     * @param resEndType the value for subs_comm.RES_END_TYPE
     *
     * @mbggenerated
     */
    public void setResEndType(String resEndType) {
        this.resEndType = resEndType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.PROV_CODE
     *
     * @return the value of subs_comm.PROV_CODE
     *
     * @mbggenerated
     */
    public String getProvCode() {
        return provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.PROV_CODE
     *
     * @param provCode the value for subs_comm.PROV_CODE
     *
     * @mbggenerated
     */
    public void setProvCode(String provCode) {
        this.provCode = provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.AREA_CODE
     *
     * @return the value of subs_comm.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.AREA_CODE
     *
     * @param areaCode the value for subs_comm.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.CREATE_DATE
     *
     * @return the value of subs_comm.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.CREATE_DATE
     *
     * @param createDate the value for subs_comm.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.EFFECTIVE_DATE
     *
     * @return the value of subs_comm.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for subs_comm.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.EXPIRE_DATE
     *
     * @return the value of subs_comm.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.EXPIRE_DATE
     *
     * @param expireDate the value for subs_comm.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_comm.OPER_ID
     *
     * @return the value of subs_comm.OPER_ID
     *
     * @mbggenerated
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_comm.OPER_ID
     *
     * @param operId the value for subs_comm.OPER_ID
     *
     * @mbggenerated
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }
}