package com.mvne.app.domain;

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subs_basic_offer
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Component
public class SubsBasicOffer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer subsElementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer subsProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.SUBS_USER_ID
     *
     * @mbggenerated
     */
    private Integer subsUserId;

    /**
     * Database Column Remarks:
     *   BSS核心:新增字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.ELEMENT_ID
     *
     * @mbggenerated
     */
    private Integer elementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.MVNO_OFFER_ID
     *
     * @mbggenerated
     */
    private Integer mvnoOfferId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.OFFER_ID
     *
     * @mbggenerated
     */
    private String offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.BASIC_OFFER_TYPE
     *
     * @mbggenerated
     */
    private String basicOfferType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.COMPONENT_ID
     *
     * @mbggenerated
     */
    private Integer componentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.EXPIRE_DATE
     *
     * @mbggenerated
     */
    private Date expireDate;

    /**
     * Database Column Remarks:
     *   回写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.OFFER_INS_ID
     *
     * @mbggenerated
     */
    private String offerInsId;

    /**
     * Database Column Remarks:
     *   回写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.RESP_STATUS
     *
     * @mbggenerated
     */
    private String respStatus;

    /**
     * Database Column Remarks:
     *   回写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.ABS_ACTIVE_DATE
     *
     * @mbggenerated
     */
    private Date absActiveDate;

    /**
     * Database Column Remarks:
     *   回写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.ABS_INACTIVE_DATE
     *
     * @mbggenerated
     */
    private Date absInactiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.PROV_CODE
     *
     * @mbggenerated
     */
    private String provCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subs_basic_offer.OPER_ID
     *
     * @mbggenerated
     */
    private Integer operId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.SUBS_ELEMENT_ID
     *
     * @return the value of subs_basic_offer.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsElementId() {
        return subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.SUBS_ELEMENT_ID
     *
     * @param subsElementId the value for subs_basic_offer.SUBS_ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setSubsElementId(Integer subsElementId) {
        this.subsElementId = subsElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.SUBS_PRODUCT_ID
     *
     * @return the value of subs_basic_offer.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getSubsProductId() {
        return subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.SUBS_PRODUCT_ID
     *
     * @param subsProductId the value for subs_basic_offer.SUBS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setSubsProductId(Integer subsProductId) {
        this.subsProductId = subsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.SUBS_USER_ID
     *
     * @return the value of subs_basic_offer.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public Integer getSubsUserId() {
        return subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.SUBS_USER_ID
     *
     * @param subsUserId the value for subs_basic_offer.SUBS_USER_ID
     *
     * @mbggenerated
     */
    public void setSubsUserId(Integer subsUserId) {
        this.subsUserId = subsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.ELEMENT_ID
     *
     * @return the value of subs_basic_offer.ELEMENT_ID
     *
     * @mbggenerated
     */
    public Integer getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.ELEMENT_ID
     *
     * @param elementId the value for subs_basic_offer.ELEMENT_ID
     *
     * @mbggenerated
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.MVNO_OFFER_ID
     *
     * @return the value of subs_basic_offer.MVNO_OFFER_ID
     *
     * @mbggenerated
     */
    public Integer getMvnoOfferId() {
        return mvnoOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.MVNO_OFFER_ID
     *
     * @param mvnoOfferId the value for subs_basic_offer.MVNO_OFFER_ID
     *
     * @mbggenerated
     */
    public void setMvnoOfferId(Integer mvnoOfferId) {
        this.mvnoOfferId = mvnoOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.OFFER_ID
     *
     * @return the value of subs_basic_offer.OFFER_ID
     *
     * @mbggenerated
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.OFFER_ID
     *
     * @param offerId the value for subs_basic_offer.OFFER_ID
     *
     * @mbggenerated
     */
    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.BASIC_OFFER_TYPE
     *
     * @return the value of subs_basic_offer.BASIC_OFFER_TYPE
     *
     * @mbggenerated
     */
    public String getBasicOfferType() {
        return basicOfferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.BASIC_OFFER_TYPE
     *
     * @param basicOfferType the value for subs_basic_offer.BASIC_OFFER_TYPE
     *
     * @mbggenerated
     */
    public void setBasicOfferType(String basicOfferType) {
        this.basicOfferType = basicOfferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.COMPONENT_ID
     *
     * @return the value of subs_basic_offer.COMPONENT_ID
     *
     * @mbggenerated
     */
    public Integer getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.COMPONENT_ID
     *
     * @param componentId the value for subs_basic_offer.COMPONENT_ID
     *
     * @mbggenerated
     */
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.CREATE_DATE
     *
     * @return the value of subs_basic_offer.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.CREATE_DATE
     *
     * @param createDate the value for subs_basic_offer.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.EFFECTIVE_DATE
     *
     * @return the value of subs_basic_offer.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for subs_basic_offer.EFFECTIVE_DATE
     *
     * @mbggenerated
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.EXPIRE_DATE
     *
     * @return the value of subs_basic_offer.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.EXPIRE_DATE
     *
     * @param expireDate the value for subs_basic_offer.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.OFFER_INS_ID
     *
     * @return the value of subs_basic_offer.OFFER_INS_ID
     *
     * @mbggenerated
     */
    public String getOfferInsId() {
        return offerInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.OFFER_INS_ID
     *
     * @param offerInsId the value for subs_basic_offer.OFFER_INS_ID
     *
     * @mbggenerated
     */
    public void setOfferInsId(String offerInsId) {
        this.offerInsId = offerInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.RESP_STATUS
     *
     * @return the value of subs_basic_offer.RESP_STATUS
     *
     * @mbggenerated
     */
    public String getRespStatus() {
        return respStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.RESP_STATUS
     *
     * @param respStatus the value for subs_basic_offer.RESP_STATUS
     *
     * @mbggenerated
     */
    public void setRespStatus(String respStatus) {
        this.respStatus = respStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.ABS_ACTIVE_DATE
     *
     * @return the value of subs_basic_offer.ABS_ACTIVE_DATE
     *
     * @mbggenerated
     */
    public Date getAbsActiveDate() {
        return absActiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.ABS_ACTIVE_DATE
     *
     * @param absActiveDate the value for subs_basic_offer.ABS_ACTIVE_DATE
     *
     * @mbggenerated
     */
    public void setAbsActiveDate(Date absActiveDate) {
        this.absActiveDate = absActiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.ABS_INACTIVE_DATE
     *
     * @return the value of subs_basic_offer.ABS_INACTIVE_DATE
     *
     * @mbggenerated
     */
    public Date getAbsInactiveDate() {
        return absInactiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.ABS_INACTIVE_DATE
     *
     * @param absInactiveDate the value for subs_basic_offer.ABS_INACTIVE_DATE
     *
     * @mbggenerated
     */
    public void setAbsInactiveDate(Date absInactiveDate) {
        this.absInactiveDate = absInactiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.PROV_CODE
     *
     * @return the value of subs_basic_offer.PROV_CODE
     *
     * @mbggenerated
     */
    public String getProvCode() {
        return provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.PROV_CODE
     *
     * @param provCode the value for subs_basic_offer.PROV_CODE
     *
     * @mbggenerated
     */
    public void setProvCode(String provCode) {
        this.provCode = provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.AREA_CODE
     *
     * @return the value of subs_basic_offer.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.AREA_CODE
     *
     * @param areaCode the value for subs_basic_offer.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subs_basic_offer.OPER_ID
     *
     * @return the value of subs_basic_offer.OPER_ID
     *
     * @mbggenerated
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subs_basic_offer.OPER_ID
     *
     * @param operId the value for subs_basic_offer.OPER_ID
     *
     * @mbggenerated
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }
}